import java.util.LinkedList;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

class Complex {
  private long real;
  private int imaginary;

  public Complex(long real, int imaginary) {
    this.real = real;
    this.imaginary = imaginary;
  }

  public long real() {
    return real;
  }
  public long imaginary() {
    return imaginary;
  }
}

class MemorySized {
  private long size;

  private List<Object> objects = new LinkedList<Object>();

  public void register(Object object) {
    objects.add(object);
  }

  public long size() {
    return size;
  }
}

public class App {
  private static long sizeof(Object object) {
    return InstrumentationAgent.deepSizeOf(object);
  }

  public static void main(String[] args) {
    long l = 42;
    int integer = 42;
    Complex complex = new Complex(42, 42);

    System.out.println("int: " + sizeof(integer));
    System.out.println("long: " + sizeof(l));
    System.out.println("complex: " + sizeof(complex));

    MemorySized register = new MemorySized();
    register.register(integer);
    System.out.println("Added int");
    System.out.println("register: " + sizeof(register));
    register.register(l);
    System.out.println("Added long");
    System.out.println("register: " + sizeof(register));
    register.register(complex);
    System.out.println("Added complex");
    System.out.println("register: " + sizeof(register));

    for (int i = 0; i < 100; i++) {
      register.register(new Integer(i));
    }
    System.out.println("register: " + sizeof(register));
  }
}
